### ISSUE TITLE
Getdown fails to download jar files when both "updates" and "stub" goals are configured

### ISSUE THREAD

**Issue by gieza** [rockfireredmoon/getdown-maven-plugin#12]
It appears that both goals are using same work directory and writing to the same "getdown.txt" file. Since Stubs goal creates shortened "getdown.txt" as compared to Updates version, there are no jar information in "getdown.txt" file, what causes update failure

**Comment by rockfireredmoon** [comment]
Thanks for the patch, will be in next release.
