### ISSUE TITLE
Implement Custom Java Installation

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/getdown-maven-plugin#3]
A minimum Java version may be specified in getdown.txt along with resource locations for alternative Java runtimes that may be downloaded (OS specific) to satisfy that requirement.

The Maven plugin should accept a minimum version configuration option (java_min_version) and location of runtime bundles and inject these into getdown.txt. The runtime bundles must be in JAR format, so in order to add value to using the Maven plugin, it should be capable of accepting of generating these jars from :-

- The current Maven Java runtime. This would obviously only be for the current platform
- File locations. Either an expanded runtime, a zip of a runtime, a jar of a runtime or a tgz of a runtime. 
- HTTP locations. A zip of a runtime, a jar of a runtime or a tgz of a runtime. 

Other configuration options that should be exposed include :-

- java_max_version
- java_exact_version_required

See https://github.com/threerings/getdown/wiki/Getdown-Dot-Text for full details

**Comment by ghost** [comment]
Fixed in #10
