### ISSUE TITLE
Manifest support

### ISSUE THREAD

**Issue by belluccifranco** [rockfireredmoon/getdown-maven-plugin#4]
I can't configure my pom with mainClass = manifest. Is this feature supported in this plugin?
This is the feature that I need to use https://github.com/threerings/getdown/wiki/Getdown-Dot-Text#launcher-configuration
(I'm currently using this option in getdown)

Thanks for your work

**Comment by belluccifranco** [comment]
**My config**
`<plugin>
                <groupId>org.icestuff</groupId>
                <artifactId>getdown-maven-plugin</artifactId>
                <version>0.0.3-SNAPSHOT</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>updates</goal>                            
                        </goals>
                        <configuration>                            
                            <appbase>https://globo-sic-ops-production.herokuapp.com/</appbase>
                            <mainClass>manifest</mainClass>                                                        
                        </configuration>                        
                    </execution>
                </executions>
            </plugin>`

**Error in console**
`[ERROR] Failed to execute goal org.icestuff:getdown-maven-plugin:0.0.3-SNAPSHOT:updates (default) on project sic-ops: didn't find artifact with main class: manifest. Did you specify it?  -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by rockfireredmoon** [comment]
You need  ..

```xml
<mainClass>com.mycompany.MyClass</mainClass>
```

AND

```xml
<ignoreMissingMain>true</ignoreMissingMain>
```

in your `<configuration>` section? If the pom.xml that contains the getdown-maven-plugin is a 'pom' type (i.e. does not contain the actual code where the main() method is),  and your main is in another project, then the plugin will not find it. The `<ignoreMissingMain>` will ignore this error and carry on normal. Iirc this is hangup from where the plugin came from the JNLP plugin, and I intend to deprecate this option at some point and replace with a better solution.
